config/routes.rb
Rails.application.routes.draw do
  resources :subreddits, param: :name
  resources :users, param: :username, except:[:new]
  resources :links

  root 'links#index'

  get 'links/:id/go' => 'links#go', as: :go
  get 'links/:id/up_vote' => 'links#up_vote', as: :up_vote
  get 'links/:id/down_vote' => 'links#down_vote', as: :down_vote
  get 'search' => 'links#search'
  get 'login' => 'user_sessions#new'
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy'
  get 'signup' => 'users#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :links
  has_many :votes
  has_many :voted_links, through: :votes, source: :link
  validates :username, :password, :email, presence: true
  validates :username, length: {maximum: 25}
  validates :password, length: {minimum: 6}
  validates_format_of :email, :with => /.+@.+\..+/i

  def self.searched_users(params)
    where("username LIKE ?", "%#{params}%")
  end

  def upvoted_links
    voted_links.where("votes.value = 1.0").uniq
  end

  def downvoted_links
    voted_links.where("votes.value = -1.0").uniq
  end

  def clicked_links
    voted_links.where("votes.value = 0.2").uniq
  end

  def to_param
    username
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @num = 1
    kaminari_links
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_path(username: @user.username), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_path(username: @user.username), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find_by username: params[:username]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :description, :email, :password)
    end

    def all_user_links
      user_generated_links
      user_liked_links
      user_disliked_links
      user_clicked_links
    end
#why not working???
    def kaminari_links
      @user_links_posts = []
      @user_links_posts += @user.links
      @user_links_posts += @user.downvoted_links
      @user_links_posts += @user.clicked_links
      @user_links_posts += @user.upvoted_links
      @user_links_posts = Kaminari.paginate_array(@user_links_posts).page(params[:page]).per(10)
      #@user_links_posts is nil. Why??
    end

    def user_generated_links
      @user_links = @user.links
    end

    def user_liked_links
      @user.upvoted_links
    end

    def user_disliked_links
      @user.downvoted_links
    end

    def user_clicked_links
      @user.clicked_links
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :username %>
    <%= f.input :password %>
    <%= f.input :email %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/_link.html.erb
<% links.each do |link|%>
<div class="row">
  <div class="col-md-1">
    <div class="row vote-image">
      <div class="col-md-2">
      <%= link_to (image_tag "up-arrow.png", class: "small-arrow"), up_vote_path(id: link.id) %>
      </div>
    </div>
    <h4 class="row vote-score"><%= link.vote_score %></h4>
    <div class="row vote-image">
      <div class="col-md-2">
      <%= link_to (image_tag "down-arrow.png", class: "small-arrow"), down_vote_path(id: link.id) %>
      </div>
    </div>
  </div>
  <div class="col-md-9">
    <h4 class="row"><%= link_to link.title, go_path(id: link.id) %> </h4>
    <div class="row">
      <h6 class="col-md-12 text-left" >Description:<%= link.summary %></h6>
    </div>
    <div class="row">
      <h6 class="col-md-10 text-left"> Submitted <%= TimeDifference.between( link.created_at,Time.now).in_hours.round %> hours ago by <%= link_to link.user.username, user_path(username: link.user.username) %> to category: <%= link_to link.subreddit.name, subreddit_path(name: link.subreddit.name) %></h6>
    </div>
  </div>
</div>
<% end %>

app/views/users/_user.html.erb
<div class="row row-margin">
  <div class="col-md-1">
    <h4 class="link-number pull-right"><%= @num %></h4>
    <% @num += 1 %>
  </div>
  <div class="col-md-8">
    <h4 class="row"><%= link_to "USER: #{user.username}", user_path(username: user.username) %> </h4>
    <div class="row">
      <h6 class="col-md-12 text-left" >Description:<%= user.description %></h6>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', user_path(username: @user.username) %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.description %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(username: user.username) %></td>
        <td><%= link_to 'Destroy', "users/#{user.username}", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', signup_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <h5 class="col-md-12"><strong>Username:</strong> <%= @user.username %></h5>
  <h5 class="col-md-12"><strong>Email:</strong> <%= @user.email %></h5>
  <h5 class="col-md-12"><strong>Description:</strong> <%= @user.description %></h5>
  <div class=col-md-12><%= link_to edit_user_path(username: @user.username), class: "btn btn-info" do %>
      <span class="glyphicon glyphicon-cogwheel"></span> SETTINGS/PROFILE
      <% end %>
  </div>
  <h5 class="col-md-12 content-border"><strong>User's Generated Content</strong></h5>
</div>

<%= render @user.links %>


<div class="row">
  <h5 class="col-md-12 content-border"><strong>User's UpVoted Content</strong></h5>
  <%= render @user_liked_links %>
</div>
<div class="row">
  <h5 class="col-md-12 content-border"><strong>User's DownVoted Content</strong></h5>
  <%= render @user_disliked_links %>
</div>
<div class="row">
  <h5 class="col-md-12 content-border"><strong>User's Clicked Content</strong></h5>
  <%= render @user_clicked_links %>
</div>

<%= @user_links_posts %>