config/routes.rb
Rails.application.routes.draw do
  resources :subreddits, param: :name
  resources :users, param: :username, except:[:new]
  resources :links

  root 'links#index'

  get 'links/:id/go' => 'links#go', as: :go
  get 'links/:id/up_vote' => 'links#up_vote', as: :up_vote
  get 'links/:id/down_vote' => 'links#down_vote', as: :down_vote
  get 'search' => 'links#search'
  get 'login' => 'user_sessions#new'
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy'
  get 'signup' => 'users#new'

end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :subreddit
  belongs_to :user
  has_many :votes
  validates :address, url: {no_local: true}
  validates :address, :title, :user, :subreddit, presence: true
  validates :title, length: {maximum: 200}

  default_scope { order(vote_score: :desc) }

  def self.searched_links(params)
    @searched_links = Link.where("summary LIKE ? OR title LIKE ?", "%#{params}%", "%#{params}%").order(vote_score: :desc)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy, :up_vote, :down_vote, :go]
  #debugging heroku heroku log -t
  # GET /links
  # GET /links.json
  def index
    @links = Link.order(vote_score: :desc).page(params[:page]).per(10)
    @num = 1 + ((@links.current_page - 1) * 10)
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  def up_vote
    if session[:user_id]
      Vote.create(value:1.0, link_id:@link.id, user_id:session[:user_id])
      redirect_to :back
    else
      redirect_to login_path
      flash.notice = "Please login or create an account in order to vote"
    end
  end

  def down_vote
    if session[:user_id]
      Vote.create(value: -1.0, link_id:@link.id, user_id:session[:user_id])
      redirect_to :back
    else
      redirect_to login_path
      flash.notice = "Please login or create an account in order to vote"
    end
  end

  def go
    if session[:user_id]
      Vote.create(value: 0.2, link_id:@link.id, user_id:session[:user_id])
    else
      Vote.create(value: 0.2, link_id:@link.id, user_id: nil)
    end
    redirect_to @link.address
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)
    add_http
    if Link.find_by address: @link.address.downcase
      new_link = Link.find_by address: @link.address
      redirect_to root_path
    else
      @link.vote_score = 0
      respond_to do |format|
        if @link.save
          format.html { redirect_to @link, notice: 'Link was successfully created.' }
          format.json { render :show, status: :created, location: @link }
        else
          format.html { render :new }
          format.json { render json: @link.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @num = 1
    @searched_links = Link.searched_links(params[:search_term])
    @searched_users = User.searched_users(params[:search_term])
    @searched_subreddits = Subreddit.searched_subreddits(params[:search_term])
    @searched_users += @searched_subreddits
    @searched_users += @searched_links
    #why does += not work instead of <<??
    # @searched_links += User.searched_users(params[:search_term])
    # @searched_links += Subreddit.searched_subreddits(params[:search_term])
    if @searched_links[0]
      @search_message = "Here are the users, subreddits, and posts that match your search terms:"
    else
      @search_message = "I'm sorry, we were not able to find any matches for your search term"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:address, :title, :summary, :vote_score, :subreddit_id, :user_id, :picture)
    end

    def add_http
      unless @link.address.downcase.start_with?("http")
        @link.address = @link.address.insert(0, "http://")
      end
    end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<%= simple_form_for link do |f| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.input :address, label: "URL" %>
  <%= f.input :picture, label: "Optional Picture" %>
  <%= f.input :title %>
  <%= f.input :summary %>
  <%= f.association :subreddit %>
  <%= f.association :user,  collection: User.all.map{|x| [x.username, x.id]}%>
  <%= f.button :submit %>
<% end %>

app/views/links/_link.html.erb
<div class="row row-margin">
  <div class="col-md-1">
    <h4 class="link-number pull-right"><%= @num %></h4>
    <% @num += 1 %>
  </div>
  <div class="col-md-1">
    <div class="row vote-image">
      <div class="col-md-2">
      <%= link_to (image_tag "up-arrow.png", class: "small-arrow"), up_vote_path(id: link.id) %>
      </div>
    </div>
    <h4 class="row vote-score"><%= link.vote_score %></h4>
    <div class="row vote-image">
      <div class="col-md-2">
      <%= link_to (image_tag "down-arrow.png", class: "small-arrow"), down_vote_path(id: link.id) %>
      </div>
    </div>
  </div>
  <div class="col-md-2">
    <%= link_to_unless(link.picture.nil?, (image_tag link.picture, class: "img-responsive"), go_path(id: link.id)) %>
  </div>
  <div class="col-md-8">
    <h4 class="row"><%= link_to link.title, go_path(id: link.id) %> </h4>
    <div class="row">
      <h6 class="col-md-12 text-left" >Description:<%= link.summary %></h6>
    </div>
    <div class="row">
      <h6 class="col-md-10 text-left"> Submitted <%= time_ago_in_words(link.created_at) %> ago by <%= link_to link.user.username, user_path(username: link.user.username) %> to category: <%= link_to link.subreddit.name, subreddit_path(name: link.subreddit.name) %></h6>
    </div>
  </div>
</div>

app/views/links/_subreddit.html.erb
<div class="row row-margin">
  <div class="col-md-1">
    <h4 class="link-number pull-right"><%= @num %></h4>
    <% @num += 1 %>
  </div>
  <div class="col-md-8">
    <h4 class="row"><%= link_to "Subreddit: #{link.name}", user_path(id: link.id) %> </h4>
    <div class="row">
      <h6 class="col-md-12 text-left" >Example Topics:
      <% link.links.take(5) do |this_link| %>
      <%= this_link.title %>,
      <% end %>
      </h6>
    </div>
  </div>
</div>

app/views/links/_user.html.erb
<div class="row row-margin">
  <div class="col-md-1">
    <h4 class="link-number pull-right"><%= @num %></h4>
    <% @num += 1 %>
  </div>
  <div class="col-md-8">
    <h4 class="row"><%= link_to "USER: #{link.username}", user_path(id: link.id) %> </h4>
    <div class="row">
      <h6 class="col-md-12 text-left" >Description:<%= link.description %></h6>
    </div>
  </div>
</div>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render partial: 'form', locals: {link: @link} %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<%= paginate @links, :window => 1 %>
<%= render @links %>
<%= paginate @links, :window => 1 %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render partial: 'form', locals: {link: @link} %>

<%= link_to 'Back', links_path %>

app/views/links/search.html.erb
<h5 class="row"><%= @search_message %></h5>
<!-- when not use "partial:", doesn't work weirdly still sends error message from inside partial"  -->
    <%= render @searched_users %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @link.address %>
</p>

<p>
  <strong>Title:</strong>
  <%= @link.title %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @link.summary %>
</p>

<p>
  <strong>Vote score:</strong>
  <%= @link.vote_score %>
</p>

<p>
  <strong>Subreddit:</strong>
  <%= @link.subreddit.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @link.user.username %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>