config/routes.rb
Rails.application.routes.draw do
  resources :subreddits, param: :name
  resources :users, param: :username, except:[:new]
  resources :links

  root 'links#index'

  get 'links/:id/go' => 'links#go', as: :go
  get 'links/:id/up_vote' => 'links#up_vote', as: :up_vote
  get 'links/:id/down_vote' => 'links#down_vote', as: :down_vote
  get 'search' => 'links#search'
  get 'login' => 'user_sessions#new'
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy'
  get 'signup' => 'users#new'

end

app/models/subreddit.rb
class Subreddit < ActiveRecord::Base
  has_many :links
  validates :name, exclusion: {in: %w(subreddits links users),
    message: "%{value} is reserved."}

  def self.searched_subreddits(params)
    where("name LIKE ?", "%#{params}%")
  end
end

app/controllers/subreddits_controller.rb
class SubredditsController < ApplicationController
  before_action :set_subreddit, only: [:show, :edit, :update, :destroy]

  # GET /subreddits
  # GET /subreddits.json
  def index
    @subreddits = Subreddit.all
    respond_to do |format|
      format.html{}
      format.json { @subreddits.to_json }
    end
  end

  # GET /subreddits/1
  # GET /subreddits/1.json
  def show
    #pagination messed up, shows same set for each page.
    @subreddit_links = @subreddit.links.sort_by{|link| link.vote_score}.reverse
    @subreddit_links_each = Kaminari.paginate_array(@subreddit_links).page(params[:page]).per(4)
  end

  # GET /subreddits/new
  def new
    @subreddit = Subreddit.new
  end

  # GET /subreddits/1/edit
  def edit
  end

  # POST /subreddits
  # POST /subreddits.json
  def create
    @subreddit = Subreddit.new(subreddit_params)

    respond_to do |format|
      if @subreddit.save
        format.html { redirect_to subreddit_path(name: @subreddit.name), notice: 'Subreddit was successfully created.' }
        format.json { render :show, status: :created, location: @subreddit }
      else
        format.html { render :new }
        format.json { render json: @subreddit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subreddits/1
  # PATCH/PUT /subreddits/1.json
  def update
    respond_to do |format|
      if @subreddit.update(subreddit_params)
        format.html { redirect_to subreddit_path(name: @subreddit.name), notice: 'Subreddit was successfully updated.' }
        format.json { render :show, status: :ok, location: @subreddit }
      else
        format.html { render :edit }
        format.json { render json: @subreddit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subreddits/1
  # DELETE /subreddits/1.json
  def destroy
    @subreddit.destroy
    respond_to do |format|
      format.html { redirect_to subreddit_path(name: @subreddit.name), notice: 'Subreddit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subreddit
      @subreddit = Subreddit.find_by name: params[:name]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subreddit_params
      params.require(:subreddit).permit(:name)
    end
end

app/helpers/subreddits_helper.rb
module SubredditsHelper
end

app/views/subreddits/_form.html.erb
<%= simple_form_for(@subreddit) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/subreddits/_link.html.erb
<% links.each do |link|%>
<div class="row">
  <div class="col-md-1">
    <div class="row vote-image">
      <div class="col-md-2">
      <%= link_to (image_tag "up-arrow.png", class: "small-arrow"), up_vote_path(id: link.id) %>
      </div>
    </div>
    <h4 class="row vote-score"><%= link.vote_score %></h4>
    <div class="row vote-image">
      <div class="col-md-2">
      <%= link_to (image_tag "down-arrow.png", class: "small-arrow"), down_vote_path(id: link.id) %>
      </div>
    </div>
  </div>
  <div class="col-md-9">
    <h4 class="row"><%= link_to link.title, go_path(id: link.id) %> </h4>
    <div class="row">
      <h6 class="col-md-12 text-left" >Description:<%= link.summary %></h6>
    </div>
    <div class="row">
      <h6 class="col-md-10 text-left"> Submitted <%= TimeDifference.between( link.created_at,Time.now).in_hours.round %> hours ago by <%= link_to link.user.username, user_path(username: link.user.username) %> to category: <%= link_to link.subreddit.name, subreddit_path(name: link.subreddit.name) %></h6>
    </div>
  </div>
</div>
<% end %>

app/views/subreddits/_subreddit.html.erb
<div class="row row-margin">
  <div class="col-md-1">
    <h4 class="link-number pull-right"><%= @num %></h4>
    <% @num += 1 %>
  </div>
  <div class="col-md-8">
    <h4 class="row"><%= link_to "Subreddit: #{subreddit.name}", subreddit_path(name: subreddit.name) %> </h4>
    <div class="row">
      <h6 class="col-md-12 text-left" >Example Topics:
      <% subreddit.links.take(5) do |this_link| %>
      <%= this_link.title %>,
      <% end %>
      </h6>
    </div>
  </div>
</div>

app/views/subreddits/edit.html.erb
<h1>Editing Subreddit</h1>

<%= render 'form' %>

<%= link_to 'Show', subreddit_path(name: @subreddit.name) %> |
<%= link_to 'Back', subreddits_path %>

app/views/subreddits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subreddits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subreddits.each do |subreddit| %>
      <tr>
        <td><%= subreddit.name %></td>
        <td><%= link_to 'Show', subreddit %></td>
        <td><%= link_to 'Edit', edit_subreddit_path(subreddit) %></td>
        <td><%= link_to 'Destroy', subreddit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subreddit', new_subreddit_path %>

app/views/subreddits/new.html.erb
<h1>New Subreddit</h1>

<%= render 'form' %>

<%= link_to 'Back', subreddits_path %>

app/views/subreddits/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <h5 class="col-md-12"><strong><%= @subreddit.name %></strong></h5>
</div>
</p>
<%= paginate @subreddit_links_each, :window => 1 %>
<%= render partial: "link", locals:{links: @subreddit_links} %>
<%= paginate @subreddit_links_each, :window => 1 %>