config/routes.rb
Rails.application.routes.draw do
  resources :subreddits, param: :name
  resources :users, param: :username, except:[:new]
  resources :links

  root 'links#index'

  get 'links/:id/go' => 'links#go', as: :go
  get 'links/:id/up_vote' => 'links#up_vote', as: :up_vote
  get 'links/:id/down_vote' => 'links#down_vote', as: :down_vote
  get 'search' => 'links#search'
  get 'login' => 'user_sessions#new'
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy'
  get 'signup' => 'users#new'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <header class="row text-center">
      <div class="col-md-10">
    <% Subreddit.all.take(13).each do |subreddit| %>
      <%=link_to subreddit.name, subreddit_path(name: subreddit.name)%> -
      <% end %>
      </div>
      <div class="col-md-2">
        <%= collection_select(:subreddit, :name, Subreddit.all, :name, :name) %>
      </div>
    </header>
    <div class="row" id="logo-bar">
      <div class="col-md-2">
        <h3><span id ="logo"><%= link_to "redditclone", root_path%></span></h3>
      </div>
    </div>
    <div class="row links-section">
      <div class="col-md-9">
        <%= yield %>
      </div>
      <div class="col-md-3">
        <div class="row">
          <form class="navbar-form navbar-left" role="search" action="/search" method="get">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search" name="search_term">
            </div>
            <button type="submit" class="btn btn-small btn-default">Submit</button>
          </form>
          <%= @current_user %>
            <%= link_to_if current_user, "Logout", logout_path, method: :delete, class: "col-md-10 col-md-offset-1 btn btn-warning btn-sm login-button" do
                link_to "Login", login_path, class: "col-md-10 col-md-offset-1 btn btn-success btn-sm login-button"
              end
                %>


        </div>
        <div class="row">
          <%= link_to (image_tag "pizza.png", class:"img-responsive"), root_path  %>
        </div>
        <div class="row">
          <%= link_to new_link_path, class: "col-md-10 col-md-offset-1 btn btn-info btn-sm side-button" do %>
            <span class="glyphicon glyphicon-pencil"></span> CREATE NEW POST
          <% end %>
          <%= link_to signup_path, class: "col-xs-10 col-xs-offset-1 btn btn-info btn-sm side-button" do %>
            <span class="glyphicon glyphicon-user"></span> CREATE NEW USER
          <% end %>
          <%= link_to new_subreddit_path, class: "col-xs-10 col-xs-offset-1 btn btn-info btn-sm side-button" do %>
            <span class="glyphicon glyphicon-heart"></span> CREATE NEW SUBREDDIT
          <% end %>
        </div>
        <div class="row side-button">
          <%= link_to (image_tag "gta.png", class:"img-responsive"), root_path  %>
        </div>
      </div>
    </div>
  </div>
</body>
</html>